apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: express-dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: express-dev
    spec:
      containers:
      - name: express-dev
        image: mydockerimages-microsoft.azurecr.io/express:latest
        env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: "b6a4c40e-f814-4e38-88e8-c40570859834"
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: azurecontainerreg
---
apiVersion: v1
kind: Service
metadata:
  name: express-dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: express-dev